version: '2'

# For full config, see also docker-compose.{override,prod}.yml

services:
  nginx:
    image: nginx:stable
    links:
      - hugo
      - kansa
    volumes:
      - ./nginx/conf.template:/nginx.conf.template:ro
    command: /bin/bash -c "envsubst '$$API_SERVER_NAME $$API_SSL_CERTIFICATE $$API_SSL_CERTIFICATE_KEY' < /nginx.conf.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"

  hugo:
    build: ./hugo/server
    entrypoint: ./wait-for-it.sh postgres:5432 -- npm start
    links:
      - postgres
    expose:
      - "3000"

  kansa:
    build: ./kansa/server
    entrypoint: ./wait-for-it.sh postgres:5432 -- npm start
    links:
      - kyyhky
      - postgres
    expose:
      - "3000"

  kyyhky:
    build: ./kyyhky
    entrypoint: ./wait-for-it.sh redis:6379 -- npm start
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
    links:
      - redis
    expose:
      - "3000"

  redis:
    image: redis:3.2
    expose:
      - "6379"

  postgres:
    build: ./postgres
    environment:
      - 'PGUSER=admin'
      - 'PGPASSWORD=adminpwd'
      - 'PGDATA=/pgdata'
      - 'POSTGRES_DB=api'
      - 'POSTGRES_USER=admin'
      - 'POSTGRES_PASSWORD=adminpwd'
      - 'KANSA_PG_PASSWORD=pwd'
      - 'HUGO_PG_PASSWORD=pwd'
    expose:
      - "5432"
    volumes:
      - pgdata:/pgdata

  postgres-replica:
    image: danieldent/postgres-replication:9.5
    environment:
      - 'REPLICATE_FROM=postgres'
      - 'PGUSER=admin'
      - 'PGPASSWORD=adminpwd'
      - 'PGDATA=/pgdata'
      - 'POSTGRES_DB=api'
      - 'POSTGRES_USER=admin'
      - 'POSTGRES_PASSWORD=adminpwd'
      - 'KANSA_PG_PASSWORD=pwd'
      - 'HUGO_PG_PASSWORD=pwd'
    expose:
      - "5432"
    restart: always
    volumes:
      - /pgdata
    links:
      - postgres

volumes:
  pgdata:
