version: '2'

# Dev setup

services:
  postgres:
    build: ../postgres-standalone
    image: arsatiki/postgres
#    env_file: .env
    ports:
      - "5432:5432"
    restart: always
    volumes:
     - ./worldcon-data/pgdata:/var/lib/postgresql/data/pgdata
     - ./entrypoint.d:/docker-entrypoint-initdb.d
    environment:
     - PGDATA=/var/lib/postgresql/data/pgdata
  
  app:
    build: ../db-api
    image: arsatiki/worldcon-db-api
    links:
      - postgres
    ports:
      - "3000:3000"
    
#  proxy:
#    build: ../proxy/
#    image: arsatiki/worldcon-api-proxy
#    ports:
#      - "80:80"
#      - "443:443"
#    links:
#     - app
#    volumes:
#     - /etc/letsencrypt:/etc/letsencrypt
#     - ../../hakkapeliitta/public/:/usr/share/nginx/html

