version: '2'

# Dev setup

services:
  postgres:
    image: postgres:9.5
    env_file: .env
    ports:
      - "5432:5432"
    restart: always
    volumes:
     - ./worldcon-data/pgdata:/var/lib/postgresql/data/pgdata
     - ./entrypoint.d:/docker-entrypoint-initdb.d
    environment:
     - PGDATA=/var/lib/postgresql/data/pgdata